RWM-P2-TEAM-C/Assets/Scenes/Game.unity
RWM-P2-TEAM-C/Packages/manifest.json
RWM-P2-TEAM-C/Packages/packages-lock.json
RWM-P2-TEAM-C/ProjectSettings/TagManager.asset

Integrated 2D movement component.
To Test:
Clone and checkout to this branch, run the game and see if it works.

Integrated 2D movement component

---

RWM-P2-TEAM-C/Assets/Scenes/Game.unity
RWM-P2-TEAM-C/Packages/manifest.json
RWM-P2-TEAM-C/Packages/packages-lock.json

I have added my [Screen Transition package](https://github.com/itcgames/RWM-ScreenTransitions) via the Package Manager.
I have added it to our main Camera in the Game scene to show it working.
Game Unity Scene - Open it and double check that the component is added successfully and that you can drag the handle gizmo on the Editor screen.

Integrated Screen Transition Component [JIRA ID: ZS-4]

---

RWM-P2-TEAM-C/Assets/Scenes/Game.unity
RWM-P2-TEAM-C/Packages/manifest.json
RWM-P2-TEAM-C/Packages/packages-lock.json
RWM-P2-TEAM-C/ProjectSettings/TagManager.asset

P1 component has been integrated into P2.

Integrated P1 component into P2

---

RWM-P2-TEAM-C/Assets/Scenes/Game.unity
RWM-P2-TEAM-C/Assets/Scripts/Bomber.cs
RWM-P2-TEAM-C/Assets/Scripts/Bomber.cs.meta
RWM-P2-TEAM-C/Assets/Tests/BomberTests.cs
RWM-P2-TEAM-C/Assets/Tests/BomberTests.cs.meta

Bomber enemy movement implementation and testing. Commits will be squashed by the merge.

Task movement

---

RWM-P2-TEAM-C/Assets/Animations/Player/Jump_Animation.anim
RWM-P2-TEAM-C/Assets/Animations/Player/Jump_Animation.anim.meta
RWM-P2-TEAM-C/Assets/Animations/Player/Player.controller
RWM-P2-TEAM-C/Assets/Scripts/PlayerController.cs
RWM-P2-TEAM-C/Assets/Tests/PlayerAnimationTests.cs

Added in the jumping animation, run the tests that are there and make sure they are all passing and also run the game and make sure the animations are correct and feel immersive.

2d jumping animation

---

RWM-P2-TEAM-C/Assets/Scenes/Game.unity
RWM-P2-TEAM-C/Assets/Scripts/Bomber.cs
RWM-P2-TEAM-C/Assets/Tests/BomberTests.cs

Task includes the implementation and testing of a bomb being spawned beneath the bomber enemy

Task bomb spawning

---

RWM-P2-TEAM-C/Assets/Scenes/Game.unity
RWM-P2-TEAM-C/Assets/Scripts/Bomb.cs
RWM-P2-TEAM-C/Assets/Scripts/Bomb.cs.meta
RWM-P2-TEAM-C/Assets/Scripts/Bomber.cs
RWM-P2-TEAM-C/Assets/Tests/BomberTests.cs

Includes implementation and testing of basic bomb movement/carrying

Task bomb carrying

---

RWM-P2-TEAM-C/Assets/Scenes/Game.unity
RWM-P2-TEAM-C/Assets/Scripts/Bomb.cs
RWM-P2-TEAM-C/Assets/Scripts/Bomb.cs.meta
RWM-P2-TEAM-C/Assets/Scripts/Bomber.cs
RWM-P2-TEAM-C/Assets/Tests/BomberTests.cs

Includes Implementation and testing of bomb froppingfunctionality when player is withen range.

Task bomb drop

---

RWM-P2-TEAM-C/Assets/Scenes/Game.unity
RWM-P2-TEAM-C/Assets/Scripts/Bomb.cs
RWM-P2-TEAM-C/Assets/Scripts/Bomb.cs.meta
RWM-P2-TEAM-C/Assets/Scripts/Bomber.cs
RWM-P2-TEAM-C/Assets/Tests/BomberTests.cs

Includes Basic Implementation and testing of bomb explosion;

Task bomb explosion

---

RWM-P2-TEAM-C/Assets/Scenes/Game.unity
RWM-P2-TEAM-C/Assets/Scenes/PlayerTestScene.unity
RWM-P2-TEAM-C/Assets/Scripts/BulletManager.cs
RWM-P2-TEAM-C/Assets/Scripts/GunManager.cs
RWM-P2-TEAM-C/Assets/Scripts/GunManager.cs.meta
RWM-P2-TEAM-C/Assets/Scripts/PlayerController.cs
RWM-P2-TEAM-C/Assets/Tests/ShootingBulletsTest.cs
RWM-P2-TEAM-C/ProjectSettings/ProjectVersion.txt

Zs-82 swap guns task implemented with tests passing

Zs-82 swap guns task implemented with tests passing

---

RWM-P2-TEAM-C/Assets/Scripts/BulletManager.cs
RWM-P2-TEAM-C/Assets/Scripts/GunManager.cs
RWM-P2-TEAM-C/Assets/Tests/GunTests.cs
RWM-P2-TEAM-C/Assets/Tests/GunTests.cs.meta

Zs 83 shooting implemented with tests passing

Zs 83 shooting implemented with tests passing

---

RWM-P2-TEAM-C/Assets/Scenes/Game.unity
RWM-P2-TEAM-C/Assets/Scenes/PlayerTestScene.unity
RWM-P2-TEAM-C/Assets/Scripts/BulletManager.cs
RWM-P2-TEAM-C/Assets/Scripts/GunManager.cs
RWM-P2-TEAM-C/Assets/Scripts/GunManager.cs.meta
RWM-P2-TEAM-C/Assets/Scripts/PlayerController.cs
RWM-P2-TEAM-C/Assets/Tests/GunTests.cs
RWM-P2-TEAM-C/Assets/Tests/GunTests.cs.meta
RWM-P2-TEAM-C/Assets/Tests/ShootingBulletsTest.cs
RWM-P2-TEAM-C/Packages/manifest.json
RWM-P2-TEAM-C/Packages/packages-lock.json
RWM-P2-TEAM-C/ProjectSettings/ProjectVersion.txt

Zs 84 life time Implemented with tests passing

Zs 84 life time Implemented with tests passing

---

RWM-P2-TEAM-C/Assets/Tests/GunTests.cs

Task Implemented with tests passing

Task Implemented with tests passing

---

RWM-P2-TEAM-C/Assets/Scenes/Game.unity
RWM-P2-TEAM-C/Assets/Scripts/Bomb.cs
RWM-P2-TEAM-C/Assets/Scripts/Bomber.cs
RWM-P2-TEAM-C/Assets/Scripts/Boss.cs
RWM-P2-TEAM-C/Assets/Scripts/BossBullet.cs
RWM-P2-TEAM-C/Assets/Scripts/Bullet.cs
RWM-P2-TEAM-C/Assets/Scripts/BulletManager.cs
RWM-P2-TEAM-C/Assets/Scripts/FlyingFollwerCollisions.cs
RWM-P2-TEAM-C/Assets/Scripts/OnDeath.cs
RWM-P2-TEAM-C/Assets/Scripts/PlayerController.cs
RWM-P2-TEAM-C/Assets/Scripts/Server/AnalyticsManager.cs
RWM-P2-TEAM-C/Assets/Scripts/Shrapnel.cs
RWM-P2-TEAM-C/Assets/Scripts/levelover.cs
RWM-P2-TEAM-C/ProjectSettings/ProjectVersion.txt

Zs 153 analytic changes Finished with tests passing

Zs 153 analytic changes Finished with tests passing

---

RWM-P2-TEAM-C/Assets/Scripts/Bullet.cs
RWM-P2-TEAM-C/Assets/Scripts/BulletManager.cs

1. Adjusted the bullet Heights to line up with the gun, and face the direction fired.
2. Bullets are destroyed when they hit a Ledge.
3. Steam Damage and Ammo adjusted for balance.

ZS-160 bullet adjust

---

RWM-P2-TEAM-C/Assets/Scenes/Game.unity

Box Collider on Fan in Level Geometry is now a Polygon Collider, and is more rounded to fit more closely to the shape of the Fan.

ZS-185 Change Box Colliders on Level Geometry

---

RWM-P2-TEAM-C/Assets/Scripts/Bomb.cs
RWM-P2-TEAM-C/Assets/Scripts/Bomber.cs
RWM-P2-TEAM-C/Assets/Scripts/Boss.cs
RWM-P2-TEAM-C/Assets/Scripts/BossBullet.cs
RWM-P2-TEAM-C/Assets/Scripts/FlyingFollwerCollisions.cs
RWM-P2-TEAM-C/Assets/Scripts/Runner.cs
RWM-P2-TEAM-C/Assets/Scripts/Server/AnalyticsManager.cs
RWM-P2-TEAM-C/Assets/Scripts/Shrapnel.cs
RWM-P2-TEAM-C/Assets/Scripts/levelover.cs

Our Analysis Manager now sends the Completion Time, Distance moved through Level, and Damage Dealt to Player by Enemies.

ZS-183 Analysis Changes

---

RWM-P2-TEAM-C/Assets/Scenes/Game.unity
RWM-P2-TEAM-C/Assets/Scripts/Server/AnalyticsManager.cs
server/game_analytics.py
server/test.py

Our server now returns Average Completion Time, Distance to Exit (using Vector2.Distance from Player to Level End Object) and Damage Dealt to Player by each Enemy.
In order to make sure everything works, you will want to use Anaconda.
In anaconda, open the server by going to our server folder, and opening Anaconda there.
Type in ' ssh -l ubuntu -i Mantas_Josh.pem 34.242.150.74 ' into the Anaconda window. This will connect you to the server.
Type ' cd server ' to move into our server folder on the server.
Type sudo docker-compose up to begin the server instance.
After doing the above, the Server will now be running, and can be tested.
Open another Anaconda window in the server folder, and follow the steps up to "Type ' cd server '..."
Once in the server folder on the server, type in ' …

ZS-184 Data Queries

---

RWM-P2-TEAM-C/Assets/Scripts/PlayerController.cs
RWM-P2-TEAM-C/Assets/Tests/BackgroundLevelTest.cs

ZS-195  implemented with tests passing

ZS-195  implemented with tests passing

---

RWM-P2-TEAM-C/Assets/Scenes/Game.unity
RWM-P2-TEAM-C/Assets/Scripts/Boss.cs
RWM-P2-TEAM-C/Assets/Scripts/PlayerController.cs

ZS-197 Feature implemented with tests passing

ZS-197 Feature implemented with tests passing
